apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # <plural>.<group>
  name: mysqls.otus.homework
spec:
  # /apis/<group>/<version>
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
              # Обязательные поля
              required:
              - image
              - database
              - password
              - storage_size
  # Обьект уровня namespace
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: mysqls
    singular: mysql
    kind: MySQL
    shortNames:
    - mss