---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dba
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dba-role
rules:
#- apiGroups: ["*"]
#  resources: ["*"]
#  verbs: ["*"]
- apiGroups: ["apps","otus.homework"]
  resources:
    - deployments
    - deployments/status
  verbs:
    - get
    - list
    - create
    - delete
    - patch
    - update
- apiGroups: ["","otus.homework"]
  resources:
    - pods
    - events
    - services
    - persistentvolumes
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - create
    - delete
    - patch
    - update
- apiGroups: ["otus.homework"]
  resources: 
    - mysqls
  verbs:
    - get
    - list
    - create
    - delete
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dba-crb
subjects:
- kind: ServiceAccount
  name: dba
  namespace: homework
roleRef:
  kind: ClusterRole
  name: dba-role
  apiGroup: rbac.authorization.k8s.io