apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress-2
  namespace: homework
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /index.html ## более подходящее rewrite правило, чем в ДЗ по сетям
spec:
  ingressClassName: nginx
  rules:
    - host: homework.otus
      http:
        paths:
        {{- toYaml .Values.ingress.paths | nindent 8}}
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-2
  namespace: homework
##clusterIP отказывается работать с настройками CNI по умолчанию в миникубе
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  selector:
    homework: 'true'
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster