apiVersion: v1
kind: ServiceAccount
metadata:
  name: homework-admin
  namespace: homeworkhelm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homework-monitoring
  namespace: homeworkhelm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homeworkhelm
  name: admins-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-metrics
subjects:
- kind: ServiceAccount
  name: homework-monitoring
  namespace: homeworkhelm
roleRef:
  kind: ClusterRole
  name: metrics-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin
  namespace: homeworkhelm
subjects:
- kind: ServiceAccount
  name: homework-admin
  namespace: homeworkhelm
roleRef:
  kind: Role
  name: admins-role
  apiGroup: rbac.authorization.k8s.io
