apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argocd
spec:
  project: otus-gitops-project
  source:
    repoURL: https://github.com/Kuber-2024-10OTUS/Valyanchik_repo.git
    targetRevision: HEAD
    path: kubernetes-networks/
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
    - CreateNamespace=true