apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  namespace: homework
spec:
  replicas: 1 
  selector:
    matchLabels:
      homework: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        homework: "true"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: configfile
          mountPath: /etc/nginx/conf.d
      - name: nginx-metrics-exporter
        image: nginx/nginx-prometheus-exporter:1.4.0
        ports:
        - containerPort: 9113      
        args: ['--nginx.scrape-uri=http://localhost:8000/stub_status']
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"  
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: homework
                operator: In
                values:
                - "true"
      volumes:
      - name: configfile
        configMap:  ##  Волюм с конфигом nginx для замены стандартного
          name: nginx-config