apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1
  namespace: homework
  labels:
    app: nginx-service-1
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - protocol: TCP
      name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 30083
  selector:
    homework: 'true'
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster