apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: "storage-class-test"