apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus-mvp-project
  namespace: cicd
spec:
  description: otus-mvp-project
  sourceRepos:
  - 'https://github.com/Kuber-2024-10OTUS/Valyanchik_repo.git'
  destinations:
  - namespace: 'app'
    server: https://kubernetes.default.svc
    name: kubernetes-admin@cluster.local
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'