apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: homework
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location /homepage {
            root   /homework;
            index  index.html index.htm;
        }
            location / {
            root   /homework;
            index  index.html index.htm;
        }
            location /conf/file {
            	root   /homework/conf;
            	try_files $uri $uri/ =404;
        }
        error_page   500 502 503 504  /50x.html;
        
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    
    }