apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command:
            - sh
            - -c
            - echo "Clear container workdir">/proc/1/fd/1 && rm /homework/* 
    volumeMounts:
    - name: workdir
      mountPath: /homework 
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: /init
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}